name: resume
description: "A new Flutter project."

publish_to: 'none' 

version: 2.0.0

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.8.0
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  layout: ^1.0.5
  visibility_detector: ^0.4.0+2
  animated_text_kit: ^4.2.3
  responsive_builder: ^0.7.1
  firebase_core: ^4.1.1
  fimber: ^0.7.0
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.1.0
  json_annotation: ^4.9.0
  firebase_analytics: ^12.0.3
  device_info_plus: ^11.3.0
  package_info_plus: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.10
  freezed: ^2.1.0
  json_serializable: ^6.8.0
  analyzer: ^7.7.1

flutter:
  uses-material-design: true
  assets: 
    - assets/lang/
    - assets/icon/ic_gmail.svg
    - assets/icon/ic_linkedin.svg
    - assets/icon/ic_github.svg
